name: Build
on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.12.3
        env:
          CARGO_REGISTRIES_CRATES_IO_PROTOCOL: "sparse"
          # We build abi3 wheels, so we only want to build once, on the lowest-supported-python
          CIBW_BUILD: "cp39-*"
          CIBW_BEFORE_ALL_LINUX: "bash ./prep-manylinux-container.sh"
          CIBW_BEFORE_ALL_MACOS: "rustup target add aarch64-apple-darwin"
          CIBW_ENVIRONMENT: 'PATH="$HOME/.cargo/bin:$PATH"'
          CIBW_ARCHS_LINUX: "x86_64"
          CIBW_ARCHS_WINDOWS: "AMD64"
          CIBW_ARCHS_MACOS: "x86_64 universal2"
        # env:
        #   CIBW_SOME_OPTION: value
        #    ...
        # with:
        #   package-dir: .
        #   output-dir: wheelhouse
        #   config-file: "{package}/pyproject.toml"

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
